server:
  port: 8888

spring:
  application:
    name: config-service
  # Configuracion del repositorio local de archivos de configuracion
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/miscursos/microservicios/proyecto06/repo-config/config-repo
