server:
  port: 8888

spring:
  application:
    name: config-service
  # Configuracion del repositorio local de archivos de configuracion
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: file:///D:/miscursos/microservicios/proyecto06/repo-config/config-repo
